---
title: "Results_viz"
author: "Madeline Berger"
date: "6/25/2020"
output: html_document
---
##Summary

This script creates visualizations of a small life cycle assessment comparing using  chemical fertilizer as a nutrient source to an alternative, fish silage, in the Galapagos. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)

#read in the data

results <- read_csv(here("/viz", "results_v1.csv")) %>%
  select(impact_category = X1, value, scenario) 

```

First graph will show the ones that seem to have the best comparison in the excel version.

```{r}

main <- results %>% 
  filter(impact_category == "non-renewable energy" | impact_category == "respiratory effects (inorganics)" | impact_category == "human toxicity" | impact_category == "terrestrial ecotoxicity" | impact_category == "climate change") %>% 
  ggplot(aes(x = impact_category, y = value, group = scenario))+
  geom_bar(aes(fill = scenario), stat = "identity", position = "dodge")+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

main
```

